name: production deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      
      - run: yarn install --frozen-lockfile
      - run: yarn run test
      - run: yarn run generate:deploy --fail-on-page-error

      - name: Temporarily disable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          branch: production

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=dist --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
          
      - name: Enable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()  # Force to always run this step to ensure "include administrators" is always turned back on
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          owner: tokyo-metropolitan-gov
          repo: covid19
          branch: production
      - name: Create GitHub release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
