name: scraping electric power consumption
on: push
  # schedule:
  # - cron: 0 6 * * *
jobs:
  scraping:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:3.141.59-vanadium
        ports:
          - 4444:4444
        volumes:
          - /dev/shm:/dev/shm
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.5'
    - name: execute
      env:
        URL: ${{ secrets.URL }}
        LOGINID: ${{ secrets.LOGINID }}
        PASSWORD: ${{ secrets.PASSWORD }}
        SPREADSHEET_KEY: ${{ secrets.SPREADSHEET_KEY }}
        GD_CLIENT_ID: ${{ secrets.GD_CLIENT_ID }}
        GD_CLIENT_SECRET: ${{ secrets.GD_CLIENT_SECRET }}
        GD_REFRESH_TOKEN: ${{ secrets.GD_REFRESH_TOKEN }}
        SELENIUM_HOST: localhost
        TZ: Asia/Tokyo
      run: |
        gem install bundler
        bundle update --bundler
        bundle install
        ruby make_config.rb
        ruby scraping.rb
        git add -A
        git commit -m "Add untracked file during workflow"
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Add report file
        committer: Peter Evans <peter-evans@users.noreply.github.com>
        author: Peter Evans <peter-evans@users.noreply.github.com>
        title: '[Example] Add report file'
        body: |
          New report
          - Contains *today's* date
          - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        labels: report, automated pr
        assignees: peter-evans
        reviewers: peter-evans
        team-reviewers: owners, maintainers
        milestone: 1
        project: Example Project
        project-column: To do
        draft: false
        branch: example-patches
        base: development
    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
        echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"